<?php

namespace App\Support;

class GigTuneParitySchema
{
    /**
     * Meta keys observed in the source plugin that must remain recognized by
     * Laravel-native logic.
     *
     * @return array<int, array{key:string,value:string}>
     */
    public static function metaKeyPairs(): array
    {
        return [
            ['key' => 'gigtune_admin_override_reliability', 'value' => ''],
            ['key' => 'gigtune_artist_rating_character_avg', 'value' => ''],
            ['key' => 'gigtune_artist_rating_character_count', 'value' => ''],
            ['key' => 'gigtune_artist_rating_performance_quality_avg', 'value' => ''],
            ['key' => 'gigtune_artist_rating_performance_quality_count', 'value' => ''],
            ['key' => 'gigtune_artist_rating_punctuality_avg', 'value' => ''],
            ['key' => 'gigtune_artist_rating_punctuality_count', 'value' => ''],
            ['key' => 'gigtune_artist_rating_submitted', 'value' => ''],
            ['key' => 'gigtune_booking_artist_completed_at', 'value' => ''],
            ['key' => 'gigtune_booking_client_confirmed_at', 'value' => ''],
            ['key' => 'gigtune_booking_completed_confirmed_at', 'value' => ''],
            ['key' => 'gigtune_booking_cost_breakdown', 'value' => ''],
            ['key' => 'gigtune_booking_flagged_unreliable', 'value' => ''],
            ['key' => 'gigtune_booking_reject_reason', 'value' => ''],
            ['key' => 'gigtune_booking_reliability_snapshot', 'value' => ''],
            ['key' => 'gigtune_booking_responded_at', 'value' => ''],
            ['key' => 'gigtune_client_bank_account_name', 'value' => ''],
            ['key' => 'gigtune_client_bank_account_number', 'value' => ''],
            ['key' => 'gigtune_client_bank_code', 'value' => ''],
            ['key' => 'gigtune_client_bank_name', 'value' => ''],
            ['key' => 'gigtune_client_banner_id', 'value' => ''],
            ['key' => 'gigtune_client_branch_code', 'value' => ''],
            ['key' => 'gigtune_client_public_id', 'value' => ''],
            ['key' => 'gigtune_client_rating_booking_completion_speed', 'value' => ''],
            ['key' => 'gigtune_client_rating_character', 'value' => ''],
            ['key' => 'gigtune_client_rating_completion_speed_hours', 'value' => ''],
            ['key' => 'gigtune_client_rating_notes', 'value' => ''],
            ['key' => 'gigtune_client_rating_payload', 'value' => ''],
            ['key' => 'gigtune_client_rating_professionalism', 'value' => ''],
            ['key' => 'gigtune_client_rating_submitted', 'value' => ''],
            ['key' => 'gigtune_client_rating_working_conditions', 'value' => ''],
            ['key' => 'gigtune_completion_reminder_sent', 'value' => ''],
            ['key' => 'gigtune_currency', 'value' => ''],
            ['key' => 'gigtune_dispute_id', 'value' => ''],
            ['key' => 'gigtune_dispute_notes', 'value' => ''],
            ['key' => 'gigtune_dispute_opened_by_role', 'value' => ''],
            ['key' => 'gigtune_dispute_opened_by_user_id', 'value' => ''],
            ['key' => 'gigtune_dispute_prev_booking_status', 'value' => ''],
            ['key' => 'gigtune_dispute_raised_at', 'value' => ''],
            ['key' => 'gigtune_email_verification_expires_at', 'value' => ''],
            ['key' => 'gigtune_email_verification_required', 'value' => ''],
            ['key' => 'gigtune_email_verification_sent_at', 'value' => ''],
            ['key' => 'gigtune_email_verification_token_hash', 'value' => ''],
            ['key' => 'gigtune_email_verified_at', 'value' => ''],
            ['key' => 'gigtune_escrow_amount', 'value' => ''],
            ['key' => 'gigtune_escrow_captured_at', 'value' => ''],
            ['key' => 'gigtune_escrow_release_at', 'value' => ''],
            ['key' => 'gigtune_escrow_status', 'value' => ''],
            ['key' => 'gigtune_failed_login_events', 'value' => ''],
            ['key' => 'gigtune_kyc_date_of_birth', 'value' => ''],
            ['key' => 'gigtune_kyc_document_access_log', 'value' => ''],
            ['key' => 'gigtune_kyc_documents', 'value' => ''],
            ['key' => 'gigtune_kyc_id_number_hash', 'value' => ''],
            ['key' => 'gigtune_kyc_restart_requested_at', 'value' => ''],
            ['key' => 'gigtune_kyc_risk_flags', 'value' => ''],
            ['key' => 'gigtune_kyc_risk_metrics', 'value' => ''],
            ['key' => 'gigtune_kyc_risk_score', 'value' => ''],
            ['key' => 'gigtune_kyc_submission_id', 'value' => ''],
            ['key' => 'gigtune_last_notified_event', 'value' => ''],
            ['key' => 'gigtune_log_action', 'value' => ''],
            ['key' => 'gigtune_log_actor_user_id', 'value' => ''],
            ['key' => 'gigtune_log_payload', 'value' => ''],
            ['key' => 'gigtune_log_target_id', 'value' => ''],
            ['key' => 'gigtune_log_target_type', 'value' => ''],
            ['key' => 'gigtune_log_timestamp', 'value' => ''],
            ['key' => 'gigtune_login_history', 'value' => ''],
            ['key' => 'gigtune_message_body', 'value' => ''],
            ['key' => 'gigtune_message_booking_id', 'value' => ''],
            ['key' => 'gigtune_message_created_at', 'value' => ''],
            ['key' => 'gigtune_notification_booking_id', 'value' => ''],
            ['key' => 'gigtune_notification_email_preferences', 'value' => ''],
            ['key' => 'gigtune_notification_email_preferences_updated_at', 'value' => ''],
            ['key' => 'gigtune_payment_accommodation_fee', 'value' => ''],
            ['key' => 'gigtune_payment_authorization_url', 'value' => ''],
            ['key' => 'gigtune_payment_created_at', 'value' => ''],
            ['key' => 'gigtune_payment_currency', 'value' => ''],
            ['key' => 'gigtune_payment_event_log', 'value' => ''],
            ['key' => 'gigtune_payment_id', 'value' => ''],
            ['key' => 'gigtune_payment_initialized_at', 'value' => ''],
            ['key' => 'gigtune_payment_intent_id', 'value' => ''],
            ['key' => 'gigtune_payment_last_ignore_reason', 'value' => ''],
            ['key' => 'gigtune_payment_paid_at', 'value' => ''],
            ['key' => 'gigtune_payment_performance_fee', 'value' => ''],
            ['key' => 'gigtune_payment_pop_attachment_id', 'value' => ''],
            ['key' => 'gigtune_payment_provider', 'value' => ''],
            ['key' => 'gigtune_payment_report_note', 'value' => ''],
            ['key' => 'gigtune_payment_service_fee', 'value' => ''],
            ['key' => 'gigtune_payment_state_log', 'value' => ''],
            ['key' => 'gigtune_payment_total_amount', 'value' => ''],
            ['key' => 'gigtune_payment_transport_fee', 'value' => ''],
            ['key' => 'gigtune_payment_window_expires_at', 'value' => ''],
            ['key' => 'gigtune_payout_created_at', 'value' => ''],
            ['key' => 'gigtune_payout_id', 'value' => ''],
            ['key' => 'gigtune_payout_last_error', 'value' => ''],
            ['key' => 'gigtune_payout_ready_admin_notified_at', 'value' => ''],
            ['key' => 'gigtune_payout_recipient_code', 'value' => ''],
            ['key' => 'gigtune_payout_released_at', 'value' => ''],
            ['key' => 'gigtune_payout_state_log', 'value' => ''],
            ['key' => 'gigtune_payout_transfer_code', 'value' => ''],
            ['key' => 'gigtune_payout_updated_at', 'value' => ''],
            ['key' => 'gigtune_paystack_event_ids', 'value' => ''],
            ['key' => 'gigtune_paystack_recipient_code', 'value' => ''],
            ['key' => 'gigtune_pending_email_change', 'value' => ''],
            ['key' => 'gigtune_pending_email_change_expires_at', 'value' => ''],
            ['key' => 'gigtune_pending_email_change_requested_at', 'value' => ''],
            ['key' => 'gigtune_pending_email_change_token_hash', 'value' => ''],
            ['key' => 'gigtune_performance_rating_count', 'value' => ''],
            ['key' => 'gigtune_post_applications', 'value' => ''],
            ['key' => 'gigtune_psa_created_at', 'value' => ''],
            ['key' => 'gigtune_psa_duration_weeks', 'value' => ''],
            ['key' => 'gigtune_psa_location_city', 'value' => ''],
            ['key' => 'gigtune_psa_location_province', 'value' => ''],
            ['key' => 'gigtune_rating_submitted', 'value' => ''],
            ['key' => 'gigtune_refund_id', 'value' => ''],
            ['key' => 'gigtune_registration_role_assigned', 'value' => ''],
            ['key' => 'gigtune_reliability_acceptance_rate', 'value' => ''],
            ['key' => 'gigtune_reliability_cancellation_rate', 'value' => ''],
            ['key' => 'gigtune_reliability_no_show_count', 'value' => ''],
            ['key' => 'gigtune_reliability_rating_count', 'value' => ''],
            ['key' => 'gigtune_reliability_response_time_hours', 'value' => ''],
            ['key' => 'gigtune_reviewed_at', 'value' => ''],
            ['key' => 'gigtune_video_duration', 'value' => ''],
            ['key' => 'gigtune_video_orientation', 'value' => ''],
            ['key' => 'gigtune_yoco_last_error', 'value' => ''],
            ['key' => 'gigtune_yoco_last_return', 'value' => ''],
            ['key' => 'gigtune_yoco_redirect_url', 'value' => ''],
            ['key' => 'gigtune_yoco_returned_at', 'value' => ''],
        ];
    }

    /**
     * Source status vocabulary used by the parity auditor.
     *
     * @return array<int, array{key:string,value:string}>
     */
    public static function sourceStatusVocabulary(): array
    {
        return [
            ['key' => 'gigtune_payment_status', 'value' => 'AWAITING_PAYMENT_CONFIRMATION'],
            ['key' => 'gigtune_payment_status', 'value' => 'CONFIRMED_HELD_PENDING_COMPLETION'],
            ['key' => 'gigtune_payment_status', 'value' => 'PENDING'],
            ['key' => 'gigtune_payment_status', 'value' => 'REJECTED_PAYMENT'],
            ['key' => 'gigtune_payment_status', 'value' => 'UNPAID'],
            ['key' => 'gigtune_payout_status', 'value' => 'FAILED'],
            ['key' => 'gigtune_payout_status', 'value' => 'PAID'],
            ['key' => 'gigtune_payout_status', 'value' => 'PENDING_MANUAL'],
            ['key' => 'gigtune_dispute_status', 'value' => 'OPEN'],
            ['key' => 'gigtune_booking_status', 'value' => 'ACCEPTED_PENDING_PAYMENT'],
            ['key' => 'gigtune_booking_status', 'value' => 'COMPLETED_BY_ARTIST'],
            ['key' => 'gigtune_booking_status', 'value' => 'COMPLETED_CONFIRMED'],
            ['key' => 'gigtune_booking_status', 'value' => 'DISPUTE_OPEN'],
            ['key' => 'gigtune_booking_status', 'value' => 'REQUESTED'],
            ['key' => 'gigtune_kyc_decision', 'value' => 'pending'],
        ];
    }
}

